compressionLevel: mixed

enableGlobalCache: false

enableMessageNames: false

nmSelfReferences: false

nodeLinker: node-modules

npmAuthToken: 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

npmPublishAccess: restricted

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
